/*
 Script de criacao das tabelas para a API TemTudo.
 Execute este arquivo no SQL Server Management Studio dentro do banco TemTudo.

 A API usa tabelas permanentes de carga, em vez de tabelas temporarias #,
 porque cada upload do CSV recebe um LOTE_ID e pode ser processado pela API.
*/

DROP TABLE IF EXISTS COMPRAS_COM;
DROP TABLE IF EXISTS MOVIMENTO_MOV;
DROP TABLE IF EXISTS ITPEDIDO_ITP;
DROP TABLE IF EXISTS PEDIDOS_PED;
DROP TABLE IF EXISTS ENTREGA_ENT;
DROP TABLE IF EXISTS CARGA_CARG;
DROP TABLE IF EXISTS PRODUTOS_PRD;
DROP TABLE IF EXISTS CLIENTES_CLI;
GO

CREATE TABLE CLIENTES_CLI (
    ID_CLIENTE INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOME VARCHAR(150) NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    CPF VARCHAR(14) NULL,
    TELEFONE VARCHAR(20) NULL
);
GO

CREATE TABLE PRODUTOS_PRD (
    ID_PRODUTO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    SKU VARCHAR(50) NOT NULL UNIQUE,
    UPC VARCHAR(50) NULL,
    NOME_PRODUTO VARCHAR(200) NULL,
    QTD_ESTOQUE INT NOT NULL CONSTRAINT DF_PRODUTOS_QTD_ESTOQUE DEFAULT 0
);
GO

CREATE TABLE CARGA_CARG (
    ID_CARGA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    LOTE_ID VARCHAR(36) NOT NULL,
    ORDER_ID VARCHAR(50) NOT NULL,
    ORDER_ITEM_ID VARCHAR(50) NOT NULL,
    PURCHASE_DATE DATETIME2 NULL,
    PAYMENTS_DATE DATETIME2 NULL,
    BUYER_EMAIL VARCHAR(150) NOT NULL,
    BUYER_NAME VARCHAR(150) NULL,
    CPF VARCHAR(14) NULL,
    BUYER_PHONE_NUMBER VARCHAR(20) NULL,
    SKU VARCHAR(50) NOT NULL,
    UPC VARCHAR(50) NULL,
    PRODUCT_NAME VARCHAR(200) NULL,
    QUANTITY_PURCHASED INT NOT NULL,
    CURRENCY VARCHAR(10) NULL,
    ITEM_PRICE DECIMAL(12,2) NOT NULL,
    SHIP_SERVICE_LEVEL VARCHAR(100) NULL,
    RECIPIENT_NAME VARCHAR(150) NULL,
    SHIP_ADDRESS_1 VARCHAR(200) NULL,
    SHIP_ADDRESS_2 VARCHAR(200) NULL,
    SHIP_ADDRESS_3 VARCHAR(200) NULL,
    SHIP_CITY VARCHAR(100) NULL,
    SHIP_STATE VARCHAR(50) NULL,
    SHIP_POSTAL_CODE VARCHAR(20) NULL,
    SHIP_COUNTRY VARCHAR(50) NULL,
    IOSS_NUMBER VARCHAR(50) NULL,
    PROCESSADO BIT NOT NULL CONSTRAINT DF_CARGA_PROCESSADO DEFAULT 0,
    DATA_IMPORTACAO DATETIME2 NOT NULL CONSTRAINT DF_CARGA_DATA_IMPORTACAO DEFAULT SYSDATETIME(),
    CONSTRAINT UQ_CARGA_LOTE_ORDER_ITEM UNIQUE (LOTE_ID, ORDER_ITEM_ID)
);
GO

CREATE TABLE ENTREGA_ENT (
    ID_ENTREGA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    LOTE_ID VARCHAR(36) NOT NULL,
    SKU VARCHAR(50) NOT NULL,
    QTD_ENTREGUE INT NOT NULL,
    DATA_ENTREGA DATETIME2 NOT NULL CONSTRAINT DF_ENTREGA_DATA DEFAULT SYSDATETIME()
);
GO

CREATE TABLE PEDIDOS_PED (
    ID_PEDIDO VARCHAR(50) NOT NULL PRIMARY KEY,
    DATA_PEDIDO DATETIME2 NULL,
    DATA_PAGAMENTO DATETIME2 NULL,
    ID_CLIENTE INT NOT NULL,
    VL_TOTAL DECIMAL(12,2) NOT NULL,
    STATUS VARCHAR(20) NULL,
    CONSTRAINT FK_PEDIDOS_CLIENTES FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES_CLI(ID_CLIENTE)
);
GO

CREATE TABLE ITPEDIDO_ITP (
    ID_ITEM INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ORDER_ITEM_ID VARCHAR(50) NOT NULL UNIQUE,
    ID_PEDIDO VARCHAR(50) NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QTD INT NOT NULL,
    VL_UNIT DECIMAL(12,2) NOT NULL,
    CONSTRAINT FK_ITPEDIDO_PEDIDOS FOREIGN KEY (ID_PEDIDO)
        REFERENCES PEDIDOS_PED(ID_PEDIDO),
    CONSTRAINT FK_ITPEDIDO_PRODUTOS FOREIGN KEY (ID_PRODUTO)
        REFERENCES PRODUTOS_PRD(ID_PRODUTO),
    CONSTRAINT UQ_ITPEDIDO_PEDIDO_ORDER_ITEM UNIQUE (ID_PEDIDO, ORDER_ITEM_ID)
);
GO

CREATE TABLE MOVIMENTO_MOV (
    ID_MOVIMENTO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_PEDIDO VARCHAR(50) NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QTD_MOVIMENTADA INT NOT NULL,
    ESTOQUE_ANTES INT NOT NULL,
    ESTOQUE_DEPOIS INT NOT NULL,
    DATA_MOVIMENTO DATETIME2 NOT NULL CONSTRAINT DF_MOVIMENTO_DATA DEFAULT SYSDATETIME(),
    CONSTRAINT FK_MOVIMENTO_PEDIDOS FOREIGN KEY (ID_PEDIDO)
        REFERENCES PEDIDOS_PED(ID_PEDIDO),
    CONSTRAINT FK_MOVIMENTO_PRODUTOS FOREIGN KEY (ID_PRODUTO)
        REFERENCES PRODUTOS_PRD(ID_PRODUTO)
);
GO

CREATE TABLE COMPRAS_COM (
    ID_COMPRA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_PEDIDO VARCHAR(50) NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QTD_SOLICITADA INT NOT NULL,
    STATUS VARCHAR(20) NOT NULL CONSTRAINT DF_COMPRAS_STATUS DEFAULT 'ABERTA',
    DATA_SOLICITACAO DATETIME2 NOT NULL CONSTRAINT DF_COMPRAS_DATA DEFAULT SYSDATETIME(),
    CONSTRAINT FK_COMPRAS_PEDIDOS FOREIGN KEY (ID_PEDIDO)
        REFERENCES PEDIDOS_PED(ID_PEDIDO),
    CONSTRAINT FK_COMPRAS_PRODUTOS FOREIGN KEY (ID_PRODUTO)
        REFERENCES PRODUTOS_PRD(ID_PRODUTO),
    CONSTRAINT UQ_COMPRA_PEDIDO_PRODUTO_STATUS UNIQUE (ID_PEDIDO, ID_PRODUTO, STATUS)
);
GO

CREATE INDEX IX_CARGA_LOTE ON CARGA_CARG(LOTE_ID);
CREATE INDEX IX_CARGA_ORDER_ID ON CARGA_CARG(ORDER_ID);
CREATE INDEX IX_CARGA_SKU ON CARGA_CARG(SKU);
CREATE INDEX IX_ENTREGA_LOTE ON ENTREGA_ENT(LOTE_ID);
CREATE INDEX IX_ENTREGA_SKU ON ENTREGA_ENT(SKU);
CREATE INDEX IX_PEDIDOS_STATUS_VALOR ON PEDIDOS_PED(STATUS, VL_TOTAL DESC, DATA_PEDIDO ASC);
CREATE INDEX IX_ITPEDIDO_PEDIDO ON ITPEDIDO_ITP(ID_PEDIDO);
CREATE INDEX IX_ITPEDIDO_PRODUTO ON ITPEDIDO_ITP(ID_PRODUTO);
CREATE INDEX IX_MOVIMENTO_PEDIDO ON MOVIMENTO_MOV(ID_PEDIDO);
CREATE INDEX IX_COMPRAS_STATUS ON COMPRAS_COM(STATUS);
GO
