SELECT * FROM CLIENTES_CLI;
SELECT * FROM PRODUTOS_PRD ORDER BY SKU;
SELECT * FROM PEDIDOS_PED ORDER BY VL_TOTAL DESC;
SELECT * FROM ITPEDIDO_ITP ORDER BY ID_PEDIDO, ORDER_ITEM_ID;
SELECT * FROM MOVIMENTO_MOV ORDER BY DATA_MOVIMENTO;
SELECT * FROM COMPRAS_COM ORDER BY DATA_SOLICITACAO;
