DROP TABLE IF EXISTS #CARGA_CARG;
DROP TABLE IF EXISTS #ENTREGA_ENT;
DROP TABLE IF EXISTS MOVIMENTO_MOV;
DROP TABLE IF EXISTS COMPRAS_COM;
DROP TABLE IF EXISTS ITPEDIDO_ITP;
DROP TABLE IF EXISTS PEDIDOS_PED;
DROP TABLE IF EXISTS CLIENTES_CLI;
DROP TABLE IF EXISTS PRODUTOS_PRD;

CREATE TABLE CLIENTES_CLI (
    ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    CPF VARCHAR(20) NULL,
    TELEFONE VARCHAR(30) NULL,
    CONSTRAINT UK_CLIENTES_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE PRODUTOS_PRD (
    ID_PRODUTO INT IDENTITY(1,1) PRIMARY KEY,
    SKU VARCHAR(50) NOT NULL,
    UPC VARCHAR(50) NULL,
    NOME_PRODUTO VARCHAR(200) NOT NULL,
    QTD_ESTOQUE INT NOT NULL CONSTRAINT DF_PRODUTOS_QTD_ESTOQUE DEFAULT 0,
    CONSTRAINT UK_PRODUTOS_SKU UNIQUE (SKU),
    CONSTRAINT CK_PRODUTOS_QTD_ESTOQUE CHECK (QTD_ESTOQUE >= 0)
);

CREATE TABLE PEDIDOS_PED (
    ID_PEDIDO VARCHAR(50) PRIMARY KEY,
    DATA_PEDIDO DATETIME NOT NULL,
    DATA_PAGAMENTO DATETIME NULL,
    ID_CLIENTE INT NOT NULL,
    CURRENCY VARCHAR(10) NULL,
    VL_TOTAL DECIMAL(12,2) NOT NULL,
    SHIP_SERVICE_LEVEL VARCHAR(100) NULL,
    SHIP_ADDRESS_1 VARCHAR(200) NULL,
    SHIP_ADDRESS_2 VARCHAR(200) NULL,
    SHIP_ADDRESS_3 VARCHAR(200) NULL,
    SHIP_CITY VARCHAR(100) NULL,
    SHIP_STATE VARCHAR(50) NULL,
    SHIP_POSTAL_CODE VARCHAR(20) NULL,
    SHIP_COUNTRY VARCHAR(50) NULL,
    STATUS VARCHAR(20) NULL,
    DATA_ATUALIZACAO_STATUS DATETIME NULL,

    CONSTRAINT FK_PEDIDOS_CLIENTES
        FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES_CLI(ID_CLIENTE),

    CONSTRAINT CK_PEDIDOS_STATUS
        CHECK (STATUS IS NULL OR STATUS IN ('ATENDIDO', 'PENDENTE'))
);
GO

CREATE TABLE ITPEDIDO_ITP (
    ID_ITEM INT IDENTITY(1,1) PRIMARY KEY,
    ORDER_ITEM_ID VARCHAR(50) NOT NULL,
    ID_PEDIDO VARCHAR(50) NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QTD INT NOT NULL,
    VL_UNIT DECIMAL(12,2) NOT NULL,

    CONSTRAINT UK_ITPEDIDO_ORDER_ITEM UNIQUE (ORDER_ITEM_ID),

    CONSTRAINT FK_ITPEDIDO_PEDIDOS
        FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS_PED(ID_PEDIDO),

    CONSTRAINT FK_ITPEDIDO_PRODUTOS
        FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS_PRD(ID_PRODUTO),

    CONSTRAINT CK_ITPEDIDO_QTD CHECK (QTD > 0),
    CONSTRAINT CK_ITPEDIDO_VL_UNIT CHECK (VL_UNIT >= 0)
);

CREATE TABLE MOVIMENTO_MOV (
    ID_MOVIMENTO INT IDENTITY(1,1) PRIMARY KEY,
    ID_PEDIDO VARCHAR(50) NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QTD_MOVIMENTADA INT NOT NULL,
    ESTOQUE_ANTES INT NOT NULL,
    ESTOQUE_DEPOIS INT NOT NULL,
    DATA_MOVIMENTO DATETIME NOT NULL CONSTRAINT DF_MOVIMENTO_DATA DEFAULT GETDATE(),

    CONSTRAINT FK_MOVIMENTO_PEDIDOS
        FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS_PED(ID_PEDIDO),

    CONSTRAINT FK_MOVIMENTO_PRODUTOS
        FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS_PRD(ID_PRODUTO),

    CONSTRAINT CK_MOVIMENTO_QTD CHECK (QTD_MOVIMENTADA > 0),
    CONSTRAINT CK_MOVIMENTO_ESTOQUE CHECK (ESTOQUE_ANTES >= 0 AND ESTOQUE_DEPOIS >= 0)
);

CREATE TABLE COMPRAS_COM (
    ID_COMPRA INT IDENTITY(1,1) PRIMARY KEY,
    ID_PEDIDO VARCHAR(50) NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QTD_SOLICITADA INT NOT NULL,
    DATA_SOLICITACAO DATETIME NOT NULL CONSTRAINT DF_COMPRAS_DATA DEFAULT GETDATE(),
    STATUS_COMPRA VARCHAR(20) NOT NULL CONSTRAINT DF_COMPRAS_STATUS DEFAULT 'ABERTA',

    CONSTRAINT FK_COMPRAS_PEDIDOS
        FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS_PED(ID_PEDIDO),

    CONSTRAINT FK_COMPRAS_PRODUTOS
        FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS_PRD(ID_PRODUTO),

    CONSTRAINT CK_COMPRAS_QTD CHECK (QTD_SOLICITADA > 0),
    CONSTRAINT CK_COMPRAS_STATUS CHECK (STATUS_COMPRA IN ('ABERTA', 'RECEBIDA', 'CANCELADA'))
);

CREATE TABLE #CARGA_CARG (
    ORDER_ID VARCHAR(50),
    ORDER_ITEM_ID VARCHAR(50),
    PURCHASE_DATE DATETIME,
    PAYMENTS_DATE DATETIME,
    BUYER_EMAIL VARCHAR(150),
    BUYER_NAME VARCHAR(150),
    CPF VARCHAR(20),
    BUYER_PHONE_NUMBER VARCHAR(30),
    SKU VARCHAR(50),
    UPC VARCHAR(50),
    PRODUCT_NAME VARCHAR(200),
    QUANTITY_PURCHASED INT,
    CURRENCY VARCHAR(10),
    ITEM_PRICE DECIMAL(12,2),
    SHIP_SERVICE_LEVEL VARCHAR(100),
    SHIP_ADDRESS_1 VARCHAR(200),
    SHIP_ADDRESS_2 VARCHAR(200),
    SHIP_ADDRESS_3 VARCHAR(200),
    SHIP_CITY VARCHAR(100),
    SHIP_STATE VARCHAR(50),
    SHIP_POSTAL_CODE VARCHAR(20),
    SHIP_COUNTRY VARCHAR(50)
);

BULK INSERT #CARGA_CARG
FROM 'C:\5SBD\AV1\CARGA.csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,
    FIELDQUOTE = '"',
    ROWTERMINATOR = '0x0a',
    CODEPAGE = '65001'
);


SELECT * FROM #CARGA_CARG;

INSERT INTO CLIENTES_CLI (NOME, EMAIL, CPF, TELEFONE)
SELECT
    MAX(C.BUYER_NAME) AS NOME,
    C.BUYER_EMAIL AS EMAIL,
    MAX(C.CPF) AS CPF,
    MAX(C.BUYER_PHONE_NUMBER) AS TELEFONE
FROM #CARGA_CARG C
LEFT JOIN CLIENTES_CLI CLI
    ON CLI.EMAIL = C.BUYER_EMAIL
WHERE C.BUYER_EMAIL IS NOT NULL
  AND CLI.EMAIL IS NULL
GROUP BY C.BUYER_EMAIL;

SELECT * FROM CLIENTES_CLI;

INSERT INTO PRODUTOS_PRD (SKU, UPC, NOME_PRODUTO, QTD_ESTOQUE)
SELECT
    C.SKU,
    MAX(C.UPC) AS UPC,
    MAX(C.PRODUCT_NAME) AS NOME_PRODUTO,
    100 AS QTD_ESTOQUE
FROM #CARGA_CARG C
LEFT JOIN PRODUTOS_PRD P
    ON P.SKU = C.SKU
WHERE C.SKU IS NOT NULL
  AND P.SKU IS NULL
GROUP BY C.SKU;

SELECT * FROM PRODUTOS_PRD;

INSERT INTO PEDIDOS_PED (
    ID_PEDIDO,
    DATA_PEDIDO,
    DATA_PAGAMENTO,
    ID_CLIENTE,
    CURRENCY,
    VL_TOTAL,
    SHIP_SERVICE_LEVEL,
    SHIP_ADDRESS_1,
    SHIP_ADDRESS_2,
    SHIP_ADDRESS_3,
    SHIP_CITY,
    SHIP_STATE,
    SHIP_POSTAL_CODE,
    SHIP_COUNTRY,
    STATUS,
    DATA_ATUALIZACAO_STATUS
)
SELECT
    C.ORDER_ID,
    MIN(C.PURCHASE_DATE) AS DATA_PEDIDO,
    MIN(C.PAYMENTS_DATE) AS DATA_PAGAMENTO,
    MAX(CLI.ID_CLIENTE) AS ID_CLIENTE,
    MAX(C.CURRENCY) AS CURRENCY,
    SUM(C.QUANTITY_PURCHASED * C.ITEM_PRICE) AS VL_TOTAL,
    MAX(C.SHIP_SERVICE_LEVEL) AS SHIP_SERVICE_LEVEL,
    MAX(C.SHIP_ADDRESS_1) AS SHIP_ADDRESS_1,
    MAX(C.SHIP_ADDRESS_2) AS SHIP_ADDRESS_2,
    MAX(C.SHIP_ADDRESS_3) AS SHIP_ADDRESS_3,
    MAX(C.SHIP_CITY) AS SHIP_CITY,
    MAX(C.SHIP_STATE) AS SHIP_STATE,
    MAX(C.SHIP_POSTAL_CODE) AS SHIP_POSTAL_CODE,
    MAX(C.SHIP_COUNTRY) AS SHIP_COUNTRY,
    NULL AS STATUS,
    NULL AS DATA_ATUALIZACAO_STATUS
FROM #CARGA_CARG C
INNER JOIN CLIENTES_CLI CLI
    ON CLI.EMAIL = C.BUYER_EMAIL
LEFT JOIN PEDIDOS_PED PED
    ON PED.ID_PEDIDO = C.ORDER_ID
WHERE C.ORDER_ID IS NOT NULL
  AND PED.ID_PEDIDO IS NULL
GROUP BY C.ORDER_ID;

SELECT * FROM PEDIDOS_PED;
SELECT * FROM #CARGA_CARG;

INSERT INTO ITPEDIDO_ITP (
    ORDER_ITEM_ID,
    ID_PEDIDO,
    ID_PRODUTO,
    QTD,
    VL_UNIT
)
SELECT
    C.ORDER_ITEM_ID,
    C.ORDER_ID,
    P.ID_PRODUTO,
    C.QUANTITY_PURCHASED,
    C.ITEM_PRICE
FROM #CARGA_CARG C
INNER JOIN PRODUTOS_PRD P
    ON P.SKU = C.SKU
LEFT JOIN ITPEDIDO_ITP I
    ON I.ORDER_ITEM_ID = C.ORDER_ITEM_ID
WHERE C.ORDER_ITEM_ID IS NOT NULL
  AND I.ORDER_ITEM_ID IS NULL;

SELECT * FROM ITPEDIDO_ITP;

SELECT *
FROM ITPEDIDO_ITP I
INNER JOIN PRODUTOS_PRD P
    ON P.ID_PRODUTO = I.ID_PRODUTO
ORDER BY I.ID_PEDIDO, I.ID_ITEM;

GO
CREATE OR ALTER PROCEDURE PRC_PROCESSAR_PEDIDOS
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE
        @V_IDPEDIDO VARCHAR(50),
        @V_IDPRODUTO INT,
        @V_QTD_NECESSARIA INT,
        @V_ESTOQUE INT,
        @V_ATENDER BIT;

    SELECT 'PEDIDOS A PROCESSAR NA PROCEDURE' AS ETAPA, ID_PEDIDO, VL_TOTAL, STATUS
    FROM PEDIDOS_PED
    WHERE STATUS IS NULL OR STATUS = 'PENDENTE'
    ORDER BY VL_TOTAL DESC, DATA_PEDIDO ASC;

    DECLARE C_PEDIDOS CURSOR LOCAL FAST_FORWARD FOR
        SELECT ID_PEDIDO
        FROM PEDIDOS_PED
        WHERE STATUS IS NULL OR STATUS = 'PENDENTE'
        ORDER BY VL_TOTAL DESC, DATA_PEDIDO ASC;

    OPEN C_PEDIDOS;
    FETCH NEXT FROM C_PEDIDOS INTO @V_IDPEDIDO;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @V_ATENDER = 1;

        /* Remove solicitacoes antigas desse pedido para recalcular a falta atual. */
        DELETE FROM COMPRAS_COM
        WHERE ID_PEDIDO = @V_IDPEDIDO
          AND STATUS_COMPRA = 'ABERTA';

        DECLARE C_ITENS_VERIFICACAO CURSOR LOCAL FAST_FORWARD FOR
            SELECT
                I.ID_PRODUTO,
                SUM(I.QTD) AS QTD_NECESSARIA
            FROM ITPEDIDO_ITP I
            WHERE I.ID_PEDIDO = @V_IDPEDIDO
            GROUP BY I.ID_PRODUTO;

        OPEN C_ITENS_VERIFICACAO;
        FETCH NEXT FROM C_ITENS_VERIFICACAO INTO @V_IDPRODUTO, @V_QTD_NECESSARIA;

        WHILE @@FETCH_STATUS = 0
        BEGIN
            SELECT @V_ESTOQUE = P.QTD_ESTOQUE
            FROM PRODUTOS_PRD P
            WHERE P.ID_PRODUTO = @V_IDPRODUTO;

            IF ISNULL(@V_ESTOQUE, 0) < @V_QTD_NECESSARIA
            BEGIN
                SET @V_ATENDER = 0;

                INSERT INTO COMPRAS_COM (
                    ID_PEDIDO,
                    ID_PRODUTO,
                    QTD_SOLICITADA
                )
                VALUES (
                    @V_IDPEDIDO,
                    @V_IDPRODUTO,
                    @V_QTD_NECESSARIA - ISNULL(@V_ESTOQUE, 0)
                );
            END;

            FETCH NEXT FROM C_ITENS_VERIFICACAO INTO @V_IDPRODUTO, @V_QTD_NECESSARIA;
        END;

        CLOSE C_ITENS_VERIFICACAO;
        DEALLOCATE C_ITENS_VERIFICACAO;

        IF @V_ATENDER = 1
        BEGIN
            /* Registra a movimentacao antes de debitar o estoque. */
            INSERT INTO MOVIMENTO_MOV (
                ID_PEDIDO,
                ID_PRODUTO,
                QTD_MOVIMENTADA,
                ESTOQUE_ANTES,
                ESTOQUE_DEPOIS
            )
            SELECT
                @V_IDPEDIDO,
                P.ID_PRODUTO,
                X.QTD_NECESSARIA,
                P.QTD_ESTOQUE,
                P.QTD_ESTOQUE - X.QTD_NECESSARIA
            FROM PRODUTOS_PRD P
            INNER JOIN (
                SELECT
                    I.ID_PRODUTO,
                    SUM(I.QTD) AS QTD_NECESSARIA
                FROM ITPEDIDO_ITP I
                WHERE I.ID_PEDIDO = @V_IDPEDIDO
                GROUP BY I.ID_PRODUTO
            ) X
                ON X.ID_PRODUTO = P.ID_PRODUTO;

            /* Debita o estoque. */
            UPDATE P
            SET P.QTD_ESTOQUE = P.QTD_ESTOQUE - X.QTD_NECESSARIA
            FROM PRODUTOS_PRD P
            INNER JOIN (
                SELECT
                    I.ID_PRODUTO,
                    SUM(I.QTD) AS QTD_NECESSARIA
                FROM ITPEDIDO_ITP I
                WHERE I.ID_PEDIDO = @V_IDPEDIDO
                GROUP BY I.ID_PRODUTO
            ) X
                ON X.ID_PRODUTO = P.ID_PRODUTO;

            UPDATE PEDIDOS_PED
            SET STATUS = 'ATENDIDO',
                DATA_ATUALIZACAO_STATUS = GETDATE()
            WHERE ID_PEDIDO = @V_IDPEDIDO;

            SELECT 'PEDIDO ATENDIDO' AS ETAPA, @V_IDPEDIDO AS ID_PEDIDO;
        END
        ELSE
        BEGIN
            UPDATE PEDIDOS_PED
            SET STATUS = 'PENDENTE',
                DATA_ATUALIZACAO_STATUS = GETDATE()
            WHERE ID_PEDIDO = @V_IDPEDIDO;

            SELECT 'PENDENTE - COMPRA GERADA' AS ETAPA, @V_IDPEDIDO AS ID_PEDIDO;
        END;

        FETCH NEXT FROM C_PEDIDOS INTO @V_IDPEDIDO;
    END;

    CLOSE C_PEDIDOS;
    DEALLOCATE C_PEDIDOS;

    SELECT 'RESUMO DE STATUS DOS PEDIDOS APOS PROCESSAMENTO' AS ETAPA, STATUS, COUNT(*) AS QTD_PEDIDOS
    FROM PEDIDOS_PED
    GROUP BY STATUS;

    SELECT 'ESTOQUE APOS PROCESSAMENTO' AS ETAPA, SKU, NOME_PRODUTO, QTD_ESTOQUE
    FROM PRODUTOS_PRD
    ORDER BY ID_PRODUTO;
END;

GO
CREATE OR ALTER PROCEDURE PRC_CARREGAR_ENTREGA_FORNECEDOR
AS
BEGIN
    SET NOCOUNT ON;

    DROP TABLE IF EXISTS #ENTREGA_ENT;

    CREATE TABLE #ENTREGA_ENT (
        SKU VARCHAR(50),
        QTD_ENTREGUE INT
    );

    BULK INSERT #ENTREGA_ENT
    FROM 'C:\5SBD\AV1\CARGA_FORNECEDOR.csv'
    WITH (
        FORMAT = 'CSV',
        FIRSTROW = 2,
        FIELDQUOTE = '"',
        ROWTERMINATOR = '0x0a',
        CODEPAGE = '65001'
    );

    SELECT 'PRODUTOS RECEBIDOS DO FORNECEDOR' AS ETAPA, *
    FROM #ENTREGA_ENT;

    UPDATE P
    SET P.QTD_ESTOQUE = P.QTD_ESTOQUE + E.QTD_ENTREGUE
    FROM PRODUTOS_PRD P
    INNER JOIN #ENTREGA_ENT E
        ON E.SKU = P.SKU;

    SELECT 'ESTOQUE APOS ENTRADA DO FORNECEDOR' AS ETAPA, P.SKU, P.NOME_PRODUTO, P.QTD_ESTOQUE
    FROM PRODUTOS_PRD P
    INNER JOIN #ENTREGA_ENT E
        ON E.SKU = P.SKU
    ORDER BY P.ID_PRODUTO;

    UPDATE C
    SET C.STATUS_COMPRA = 'RECEBIDA'
    FROM COMPRAS_COM C
    INNER JOIN PRODUTOS_PRD P
        ON P.ID_PRODUTO = C.ID_PRODUTO
    INNER JOIN #ENTREGA_ENT E
        ON E.SKU = P.SKU
    WHERE C.STATUS_COMPRA = 'ABERTA';

    SELECT 'COMPRAS ATUALIZADAS APOS ENTREGA DO FORNECEDOR' AS ETAPA, C.*
    FROM COMPRAS_COM C
    INNER JOIN PRODUTOS_PRD P
        ON P.ID_PRODUTO = C.ID_PRODUTO
    INNER JOIN #ENTREGA_ENT E
        ON E.SKU = P.SKU
    ORDER BY C.ID_COMPRA;
END;
GO

SELECT 'SITUACAO ANTES DO PRIMEIRO PROCESSAMENTO' AS ETAPA, ID_PEDIDO, VL_TOTAL, STATUS
FROM PEDIDOS_PED
ORDER BY VL_TOTAL DESC, DATA_PEDIDO ASC;

EXEC PRC_PROCESSAR_PEDIDOS;

SELECT 'PEDIDOS APOS PRIMEIRO PROCESSAMENTO' AS ETAPA, *
FROM PEDIDOS_PED
ORDER BY VL_TOTAL DESC, DATA_PEDIDO ASC;

SELECT 'MOVIMENTACOES APOS PRIMEIRO PROCESSAMENTO' AS ETAPA, *
FROM MOVIMENTO_MOV
ORDER BY DATA_MOVIMENTO, ID_MOVIMENTO;

SELECT 'COMPRAS GERADAS APOS PRIMEIRO PROCESSAMENTO' AS ETAPA, C.ID_COMPRA, C.ID_PEDIDO, P.SKU, P.NOME_PRODUTO, C.QTD_SOLICITADA, C.STATUS_COMPRA
FROM COMPRAS_COM C
INNER JOIN PRODUTOS_PRD P
    ON P.ID_PRODUTO = C.ID_PRODUTO
ORDER BY C.ID_COMPRA;


EXEC PRC_CARREGAR_ENTREGA_FORNECEDOR;

SELECT 'ESTOQUE APOS PROCEDURE DO FORNECEDOR' AS ETAPA, *
FROM PRODUTOS_PRD
ORDER BY ID_PRODUTO;

/* Reprocessamento: pedidos pendentes podem ser atendidos apos entrada no estoque. */
EXEC PRC_PROCESSAR_PEDIDOS;

SELECT 'CLIENTES - RESULTADO FINAL' AS ETAPA, * FROM CLIENTES_CLI ORDER BY ID_CLIENTE;
SELECT 'PRODUTOS - RESULTADO FINAL' AS ETAPA, * FROM PRODUTOS_PRD ORDER BY ID_PRODUTO;
SELECT 'PEDIDOS - RESULTADO FINAL' AS ETAPA, * FROM PEDIDOS_PED ORDER BY VL_TOTAL DESC, DATA_PEDIDO ASC;
SELECT 'ITENS DE PEDIDO - RESULTADO FINAL' AS ETAPA, * FROM ITPEDIDO_ITP ORDER BY ID_PEDIDO, ID_ITEM;
SELECT 'MOVIMENTACAO DE ESTOQUE - RESULTADO FINAL' AS ETAPA, * FROM MOVIMENTO_MOV ORDER BY DATA_MOVIMENTO, ID_MOVIMENTO;
SELECT 'COMPRAS - RESULTADO FINAL' AS ETAPA, * FROM COMPRAS_COM ORDER BY DATA_SOLICITACAO, ID_COMPRA;
